### ISSUE TITLE
Suggestions about the "hopper" part of the blocks and custom inputs/outputs

### ISSUE THREAD

**Issue by AR-E** [jeremiahwinsley/ExMachinis#1]
When any machine that accepts input from the top has an inventory block on top of it (i.e, chests, barrels, drawers), the machine gets this "hopper" that automatically pulls items from said inventory block (as shown in the picture below). I like that this is a feature, but I think it would be better if there was some way to remove that hopper, whether that's via an addition to the GUI or some kind of wrench or tool.

Here's an image of how the "hopper" can get in the way (and even though working around this would be fairly simple, I just feel like my suggestion would be good for the sake of convenience):
![image](https://user-images.githubusercontent.com/52563078/184540104-fd98602b-beab-4c44-8415-bc100f869d64.png)

Another addition I feel would be helpful is custom inputs and outputs (sort of like how they're done in Thermal Series and in Iron Furnaces). However, that's not to say the way they work now isn't cool, I do like how you took the blocks' models into account when deciding that. It's just that they limit automation and force the user to take extra steps, which is a bit annoying.

Of course, if there are already workarounds to these two issues, then forget everything I said. If so, could you add that information to the mod page or the wiki of this GitHub page? I wasn't really able to find much information about this, which is why I opened this issue in the first place. 

Thanks for reading through this!

**Comment by jeremiahwinsley** [comment]
I do plan to make the output side selectable. I don't want to overcomplicate the settings on this, so at this time I don't plan to change the input.

**Comment by jeremiahwinsley** [comment]
As of 1.0.3 the output side is now selectable. I do not plan to make any changes to the input side.
