### ISSUE TITLE
Sieves should perform rolls separately, rather than performing one and multiplying

### ISSUE THREAD

**Issue by sctjkc01** [jeremiahwinsley/ExMachinis#11]
When you manually sieve with a 5x5 set of sieves, you consume 25 blocks of material to produce 25 rolls of whatever that material produces.  This means you have 25 chances of getting that low-chance item you really need.

However, when you throw 64 blocks of material into an auto-sieve from Ex Machinis, you only get one roll, whose result is multiplied by 64.  In the long run that might be roughly equivalent, however, when you don't have much of the original material it doesn't feel great when you sieve a handful of stacks of stuff but do not get that one low-chance item you needed.

I'd suggest that upgraded auto-sieves should perform each roll for each input block separately, so it feels a little more equivalent.

**Comment by jeremiahwinsley** [comment]
I don't plan to change this, here's why:

Ex Machinis is designed specifically for automation. Yes, in smaller quantities this can seem much harder to get the specific thing that you want, but I would argue at that step it is reasonable to sieve manually, or without upgrades. By the time you are using a max level upgrade, you should be able to have a consistent supply of the block you are automating, so averaging the chance over thousands of blocks is just minutes of auto-sieving.

Switching to rolling per single item greatly increases the number of rolls needed, which is not always a cheap operation. And the whole reason I made this mod in the first place was performance.

Switching to rolling per item can also greatly increase the number of stacks produced. Not always an issue, but with Fortune 7 people are already running into this occasionally, changing that would lead to a lot more deleted drops.

And finally, I personally much prefer getting even numbers of ore pieces so I'm not stuck with odd numbers in the compactors.

**Comment by Spongman** [comment]
yeah, this is a real bummer. i'd much prefer it if it was a random chance per item instead of per stack. direwolf20 said as much in his playthrough.
