### ISSUE TITLE
Flux Sieve not recognizing output inventory

### ISSUE THREAD

**Issue by WhyTheF8CKis-ICMan-NotAvailable** [jeremiahwinsley/ExMachinis#12]
I am using the latest version of ATM7 (1.1.2).

Flux Sieve shows error in the GUI when you mouse over the "X" saying "Missing inventory on output side".  Happens no matter which side I put either a minecraft chest or minecraft barrel.  I even put the inventory on the top and bottom.  Does not matter if I place the inventory first or the flux sieve first.  No error log, as one is not generated.  The flux sieve is simply not working as it should.

Ex Machinis v 1.0.3 (which is not on your list of available versions, coincidentally)
Forge 40.1.80

**Comment by jeremiahwinsley** [comment]
The default output side is the bottom. Note that the error only updates at the end of a work cycle currently (the green bar) so you may have to wait for one to complete for it to notice the update.

**Comment by WhyTheF8CKis-ICMan-NotAvailable** [comment]
Thank you.  Can this be configured?

**Comment by jeremiahwinsley** [comment]
The output side can be configured by shift right clicking with an Ex Nihilo hammer
