### ISSUE TITLE
Block Updating

### ISSUE THREAD

**Issue by ErfinderLabyrinth** [jeremiahwinsley/ExMachinis#13]
If I place the Flux hammer first and than the Chest, it is not accepted

Please check the errors every blockupdate

**Comment by jeremiahwinsley** [comment]
Duplicate of #4 - validation is currently done at the beginning of a work cycle, so it can take up to 8 seconds for the error to go away. I do plan to make it run more often,

**Comment by ErfinderLabyrinth** [comment]
sorry i have no read the other post, only the title
