### ISSUE TITLE
flux sieve 

### ISSUE THREAD

**Issue by drmorgmd** [jeremiahwinsley/ExMachinis#14]
Ok so kind of hard to explain but let me try. 
1. I am making a 1.19.2 pack and I have already changed the sieve recipes using kubejs
2. I was testing out the flux sieve when I noticed the output was all one item
3. with netherite upgrade (waterlogged or not) if I put in a stack of gravel you will only get one roll on an item what I mean is let's say diamond is a 10% chance, and it hits then you will receive 64 diamonds. When the sieve sifts the stack, it does it as one item and multiples the results instead of single items with normal results. 
4. This happens on all the upgrades, so gold will do the 2/4/8 as stacks of 2/4/8 instead of doing the rolls separate. 

I hope I explained it correctly, and I am on 1.19.2 with forge 43.2.0 and version 1.19.2-2.0.1

Summary: when sieving more than one item at a time it only rolls the loot table once and multiplies results.

**Comment by jeremiahwinsley** [comment]
This is by design, please see #11 for more info.

**Comment by drmorgmd** [comment]
ok so i read why you did what you did. I do have a counter to it but as it is your mod you can do as you please, however would a config option for the bonus sieve be out of the question too?

**Comment by jeremiahwinsley** [comment]
I don't think I'll change it but you're welcome to bring up any counter considerations. By bonus sieve do you mean #5 or something else?

**Comment by drmorgmd** [comment]
so my counter would be that by the time you get to the auto sieve usually you are starting to get into some other ore production miner or mystical crops and the auto sieve will be a mid game step so manual sieve to auto sieve to magic crops. 

with the config option that would allow pack devs to utilize it accordingly to their pack so if their pack is a light low mod pack then the default option will work but if their pack is a heavy pack then they could turn the option to roll individuals 

by bonus I was looking at the json file and was thinking thats how you set it up. (probably wrong)

**Comment by jeremiahwinsley** [comment]
Ah, I see, a config option to enable the individual rolling. I think I may be able to do that, I'll take a look.

**Comment by drmorgmd** [comment]
Awesome, I will look forward to seeing it.

**Comment by jeremiahwinsley** [comment]
This has been released in versions 1.1.0/2.1.0.
