### ISSUE TITLE
Off Switch/Redstone Signal Stop Enhancement

### ISSUE THREAD

**Issue by corhean** [jeremiahwinsley/ExMachinis#15]
The system should have the ability to tell the blocks to stop working, even if they have material in the buffer for item management.  A couple ideas include a strong redstone signal from a side and/or a manual switch inside the GUI to turn on/off the system; this would allow the system to be used in multiple ways (either feed items in as needed or turn on as needed with an already full system).

**Comment by jeremiahwinsley** [comment]
This is actually supported already. You can disable machines with a redstone signal.
