### ISSUE TITLE
support rei

### ISSUE THREAD

**Issue by MisileLab** [jeremiahwinsley/ExMachinis#24]
plz

**Comment by jeremiahwinsley** [comment]
REI should already work with JEI plugins, you might need REIPC also. Or is there something specific that still doesn't work in REI?

**Comment by MisileLab** [comment]
Umm it working with reipc but native support would be good

**Comment by jeremiahwinsley** [comment]
After looking into it, I rely partly on Ex Nihilo's JEI support, and they do not have separate REI support. I would need that in order to implement it on my end. So currently I do not plan to add this.
