### ISSUE TITLE
Hammer / Sieve does not accept cables from pipez mod as output

### ISSUE THREAD

**Issue by fefocwb** [jeremiahwinsley/ExMachinis#8]
Using "All the mods 7 to the sky" and trying to put an "item pipe" from pipez on the Flux Hammer exit. With no item in the machine inventory it says "machine is working" however if I put a cobblestone it goes to error saying "inventory is full" even when the other point of the pipe is a chest or the Flux Sieve.

**Comment by jeremiahwinsley** [comment]
Pipez does not actually have an inventory that the hammer can insert into, so that working message is misleading. I'll update the validator so that it doesn't mark that as valid.

**Comment by jeremiahwinsley** [comment]
As of 1.0.2 Pipez are no longer shown as valid.
